### ISSUE TITLE
URL broken in .psqlrc comments

### ISSUE THREAD

**Issue by hjhart** [datachomp/dotfiles#2]
I was looking to use these functions and was hopeful to read this blogpost but it appears to be missing!

https://github.com/datachomp/dotfiles/blob/e5c3adb27966b9b1dfef1aa0f726ff5ab9f93d4b/.psqlrc#L53

**Comment by datachomp** [comment]
That is pretty sucky.   Thank for finding this - were you ultimately able to find the info you needed on the queries?

**Comment by hjhart** [comment]
I'm sure I did long ago, but I don't think I ever found which helpful queries you guys were referring to. :)
